# Generated by Django 3.2.7 on 2021-09-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jordan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('original_release', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
