# Generated by Django 3.2.7 on 2021-09-12 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jordans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jordan',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_jordans', to=settings.AUTH_USER_MODEL),
        ),
    ]
