# Generated by Django 3.2.7 on 2021-09-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jordans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jordan',
            old_name='original_release',
            new_name='release_date',
        ),
    ]
