# Generated by Django 3.2.7 on 2021-09-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jordans', '0002_rename_original_release_jordan_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jordan',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
